# Generated by Django 6.0.1 on 2026-01-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctornotification',
            name='related_object_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patientnotification',
            name='related_object_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='secretarynotification',
            name='related_object_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
