# Generated by Django 6.0.1 on 2026-01-15 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_booking_rating_remove_appointment_doctor_and_more'),
        ('users', '0002_remove_secretaryprofile_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='users.doctor'),
        ),
        migrations.AddField(
            model_name='booking',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='users.patient'),
        ),
        migrations.AddField(
            model_name='booking',
            name='rescheduled_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_to_booking', to='clinic.booking'),
        ),
        migrations.AddField(
            model_name='rating',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='clinic.booking'),
        ),
        migrations.AddField(
            model_name='rating',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='users.doctor'),
        ),
        migrations.AddField(
            model_name='rating',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='users.patient'),
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
