# Generated by Django 6.0.1 on 2026-01-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_booking_doctor_booking_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('NEW', 'New Patient'), ('FOLLOWUP', 'Follow-up')], default='NEW', max_length=20),
        ),
    ]
