# Generated by Django 6.0.1 on 2026-01-15 21:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_booking_booking_type'),
        ('users', '0007_secretary_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('NO_SHOW', 'No Show'), ('RESCHEDULING_PENDING', 'Rescheduling Pending')], default='PENDING', max_length=30),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('BOOKING_CREATED', 'Booking Created'), ('BOOKING_APPROVED', 'Booking Approved'), ('BOOKING_REJECTED', 'Booking Rejected'), ('BOOKING_CANCELLED', 'Booking Cancelled'), ('BOOKING_RESCHEDULED', 'Booking Rescheduled'), ('CHECK_IN', 'Patient Check-in'), ('EXAM_STARTED', 'Exam Started'), ('EXAM_COMPLETED', 'Exam Completed'), ('NO_SHOW', 'No Show Recorded'), ('SECRETARY_ADDED', 'Secretary Added'), ('SECRETARY_REMOVED', 'Secretary Removed'), ('SECRETARY_UPDATED', 'Secretary Updated')], max_length=50)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='users.doctor')),
            ],
        ),
    ]
