# Generated by Django 6.0.1 on 2026-01-15 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_alter_booking_status_activitylog'),
        ('users', '0007_secretary_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_walkin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='walkin_patient_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='walkin_patient_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('BOOKING_CREATED', 'Booking Created'), ('BOOKING_APPROVED', 'Booking Approved'), ('BOOKING_REJECTED', 'Booking Rejected'), ('BOOKING_CANCELLED', 'Booking Cancelled'), ('BOOKING_RESCHEDULED', 'Booking Rescheduled'), ('CHECK_IN', 'Patient Check-in'), ('EXAM_STARTED', 'Exam Started'), ('EXAM_COMPLETED', 'Exam Completed'), ('NO_SHOW', 'No Show Recorded'), ('WALKIN_ADDED', 'Walk-in Patient Added'), ('SECRETARY_ADDED', 'Secretary Added'), ('SECRETARY_REMOVED', 'Secretary Removed'), ('SECRETARY_UPDATED', 'Secretary Updated')], max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='users.patient'),
        ),
    ]
