# Generated by Django 6.0.1 on 2026-01-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_booking_is_walkin_booking_walkin_patient_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('NO_SHOW', 'No Show'), ('EXPIRED', 'Expired - No Action Taken'), ('RESCHEDULING_PENDING', 'Rescheduling Pending')], default='PENDING', max_length=30),
        ),
    ]
