# Generated by Django 6.0.1 on 2026-01-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0009_booking_number_of_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_overflow',
            field=models.BooleanField(default=False),
        ),
    ]
