# Generated by Django 6.0.1 on 2026-01-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoravailability',
            name='max_patients_per_slot',
            field=models.IntegerField(default=1),
        ),
    ]
