# Generated by Django 6.0.1 on 2026-01-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_doctoravailability_max_patients_per_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeoff',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeoff',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeoff',
            name='suggestion_expiry',
            field=models.CharField(choices=[('1_DAY', '1 Day'), ('2_DAYS', '2 Days'), ('1_WEEK', '1 Week')], default='2_DAYS', max_length=20),
        ),
    ]
