# Generated by Django 6.0.1 on 2026-01-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_timeoff_end_time_timeoff_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeoff',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20),
        ),
    ]
