# Generated by Django 6.0.1 on 2026-01-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_timeoff_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeoff',
            name='type',
            field=models.CharField(choices=[('ABSENCE', 'Absence'), ('DIGITAL_UNAVAILABLE', 'Digital Unavailable')], default='ABSENCE', max_length=20),
        ),
    ]
