# Generated by Django 6.0.1 on 2026-01-17 16:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_timeoff_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoravailability',
            name='max_patients_per_slot',
            field=models.PositiveIntegerField(default=1, help_text='الحد الأقصى للمرضى في الموعد الواحد (1-20)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
