# Generated by Django 6.0.1 on 2026-03-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_alter_doctoravailability_max_patients_per_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeoff',
            name='suggestion_expiry',
        ),
        migrations.AddField(
            model_name='reschedulingrequest',
            name='reserved_bookings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='timeoff',
            name='expiry_fraction',
            field=models.CharField(choices=[('QUARTER', 'Quarter (1/4)'), ('HALF', 'Half (1/2)')], default='HALF', max_length=20),
        ),
    ]
