# Generated by Django 6.0.1 on 2026-01-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_phone_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='landmark',
            field=models.CharField(blank=True, help_text='Nearby landmark for easy finding', max_length=255),
        ),
        migrations.AddField(
            model_name='doctor',
            name='location',
            field=models.CharField(blank=True, help_text='Clinic address', max_length=255),
        ),
    ]
