# Generated by Django 6.0.1 on 2026-01-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_doctor_latitude_doctor_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='facebook',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='doctor',
            name='instagram',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='doctor',
            name='tiktok',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='doctor',
            name='twitter',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='doctor',
            name='youtube',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
