# Generated by Django 6.0.1 on 2026-01-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_doctor_facebook_doctor_instagram_doctor_tiktok_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretary',
            name='permissions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
