# Generated by Django 6.0.1 on 2026-01-16 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_secretary_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='allow_overbooking',
            field=models.BooleanField(default=False, help_text='Allow adding patients beyond calculated limit'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='preferred_calendar_view',
            field=models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='WEEKLY', max_length=10),
        ),
        migrations.AddField(
            model_name='doctor',
            name='session_duration',
            field=models.PositiveIntegerField(default=480, help_text='Working session duration in minutes (e.g., 480 = 8 hours)'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='time_per_patient',
            field=models.PositiveIntegerField(default=15, help_text='Average time per patient in minutes'),
        ),
    ]
