# Generated by Django 6.0.1 on 2026-01-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_doctor_allow_overbooking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='booking_cutoff_hours',
            field=models.PositiveIntegerField(default=1, help_text='Minimum hours before appointment to allow booking'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='booking_visibility_weeks',
            field=models.PositiveIntegerField(choices=[(1, '1 Week'), (2, '2 Weeks'), (3, '3 Weeks'), (4, '1 Month')], default=4, help_text='How many weeks in advance patients can see availability'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='is_digital_booking_active',
            field=models.BooleanField(default=True, help_text='Master switch for digital bookings'),
        ),
    ]
