# Generated by Django 6.0.1 on 2026-01-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_doctor_booking_cutoff_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='auto_approve_bookings',
            field=models.BooleanField(default=False, help_text='Automatically approve incoming bookings'),
        ),
    ]
