# Generated by Django 6.0.1 on 2026-01-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_doctor_auto_approve_bookings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
