# Generated by Django 6.0.1 on 2026-01-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_doctor_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=10),
        ),
        migrations.AddField(
            model_name='doctor',
            name='license_image',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_licenses/'),
        ),
    ]
