# Generated by Django 6.0.1 on 2026-02-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_doctor_gender_doctor_license_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_booking_cutoff_active',
            field=models.BooleanField(default=True, help_text='Turn off to bypass booking cutoff hours'),
        ),
    ]
