# Generated by Django 6.0.1 on 2026-03-10 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_user_deleted_at_user_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='maps_link',
            field=models.URLField(blank=True, help_text='Google Maps Link', max_length=500, null=True),
        ),
    ]
