# Generated by Django 6.0.1 on 2026-03-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_doctor_maps_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='booking_visibility_weeks',
            field=models.PositiveIntegerField(choices=[(1, '1 Week'), (2, '2 Weeks'), (3, '3 Weeks'), (4, '4 Weeks'), (5, '5 Weeks'), (6, '6 Weeks'), (7, '7 Weeks'), (8, '8 Weeks'), (9, '9 Weeks'), (10, '10 Weeks'), (11, '11 Weeks'), (12, '12 Weeks'), (13, '13 Weeks'), (14, '14 Weeks'), (15, '15 Weeks'), (16, '16 Weeks'), (17, '17 Weeks'), (18, '18 Weeks'), (19, '19 Weeks'), (20, '20 Weeks')], default=4, help_text='How many weeks in advance patients can see availability'),
        ),
    ]
